openapi: 3.0.3
info:
  version: 1.0.0
  title: ACME-Explorer API REST
  description: API REST for travel agency

paths:
  /api/v1/trips:
    get:
      description: Returns all trips
      operationId: getTrip
      responses:
        200:
          description: Trip list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/trip"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Creates a new trip
      operationId: addTrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trip"
        description: Trip to be created
        required: true
      responses:
        201:
          description: Trip
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{_id}:
    get:
      description: Returns a single trip by its _id
      operationId: findBy_id
      parameters:
        - required: true
          name: _id
          description: _id of the trip to fetch
          in: path
          schema:
            type: string
      responses:
        200:
          description: Trip found by _id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trip"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Update a trip based on its _id
      operationId: updateTrip
      parameters:
        - required: true
          name: _id
          description: _id of the trip to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trip"
        description: Trip to be updated
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      description: Deletes a single trip based on its _id
      operationId: deleteTrip
      parameters:
        - required: true
          name: _id
          description: _id of the trip to delete
          in: path
          schema:
            type: string
      responses:
        "204":
          description: Trip deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  $ref:
    - "./components/schemas/actor.yaml"
    - "./components/schemas/application.yaml"
    - "./components/schemas/trip.yaml"
    - "./components/schemas/configuration.yaml"
    - "./components/schemas/error.yaml"
    - "./components/schemas/validation-error.yaml"
    - "./components/schemas/not-found-error.yaml"
    - "./components/schemas/datawarehouse.yaml"