openapi: 3.0.3
info:
  version: 1.0.0
  title: ACME-Explorer API REST
  description: API REST for travel agency

paths:
  /api/v1/finders:
    get:
      description: Returns all finders
      operationId: getFinder
      responses:
        200:
          description: Finder list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finder"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Creates a new finder
      operationId: addFinder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                explorer_id:
                  type: string
                date:
                  type: string
                keyword:
                  type: string
                minPrice:
                  type: number
                maxPrice:
                  type: number
                startDate:
                  type: string
                endDate:
                  type: string
        description: Finder to be created
        required: true
      responses:
        201:
          description: Finder
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/finders/{_id}:
    get:
      description: Returns a single finder by its _id
      operationId: findBy_id
      parameters:
        - required: true
          name: _id
          description: _id of the finder to fetch
          in: path
          schema:
            type: string
      responses:
        200:
          description: Finder found by _id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/finder"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Update a finder based on its _id
      operationId: updateFinder
      parameters:
        - required: true
          name: _id
          description: _id of the finder to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                keyword:
                  type: string
                minPrice:
                  type: number
                maxPrice:
                  type: number
                startDate:
                  type: string
                endDate:
                  type: string
        description: Finder to be updated
        required: true
      responses:
        "204":
          description: Finder updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      description: Deletes a single finder based on its _id
      operationId: deleteFinder
      parameters:
        - required: true
          name: _id
          description: _id of the finder to delete
          in: path
          schema:
            type: string
      responses:
        "204":
          description: Finder deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/configurations:
    get:
      description: Returns all configurations
      operationId: getConfiguration
      responses:
        200:
          description: Configuration list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/configuration"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Creates a new configuration
      operationId: addConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/configuration"
        description: Configuration to be created
        required: true
      responses:
        201:
          description: Configuration
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/configurations/{_id}:
    get:
      description: Returns a single configuration by its _id
      operationId: findBy_id
      parameters:
        - required: true
          name: _id
          description: _id of the configuration to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Configuration found by _id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/configuration"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Update a configuration based on its _id
      operationId: updateConfiguration
      parameters:
        - required: true
          name: _id
          description: _id of the configuration to update
          in: path
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/configuration"
        description: Configuration to be updated
        required: true
      responses:
        "204":
          description: Configuration updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      description: Deletes a single configuration based on its _id
      operationId: deleteConfiguration
      parameters:
        - required: true
          name: _id
          description: _id of the configuration to delete
          in: path
          schema:
            type: number
      responses:
        "204":
          description: Configuration deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  $ref:
    - "./components/schemas/actor.yaml"
    - "./components/schemas/application.yaml"
    - "./components/schemas/finder.yaml"
    - "./components/schemas/trip.yaml"
    - "./components/schemas/configuration.yaml"
    - "./components/schemas/error.yaml"
    - "./components/schemas/validation-error.yaml"
    - "./components/schemas/not-found-error.yaml"
