openapi: 3.0.3
info:
  version: 1.0.0
  title: ACME-Explorer API REST
  description: API REST for travel agency

paths:
  /api/v1/finders:
    get:
      description: Returns all finders
      operationId: getFinder
      responses:
        200:
          description: Finder list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/finder"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Creates a new finder
      operationId: addFinder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                explorer_id:
                  type: string
                date:
                  type: string
                keyword:
                  type: string
                minPrice:
                  type: number
                maxPrice:
                  type: number
                startDate:
                  type: string
                endDate:
                  type: string
        description: Finder to be created
        required: true
      responses:
        201:
          description: Finder
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/finders/{_id}:
    get:
      description: Returns a single finder by its _id
      operationId: findBy_id
      parameters:
        - required: true
          name: _id
          description: _id of the finder to fetch
          in: path
          schema:
            type: string
      responses:
        200:
          description: Finder found by _id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/finder"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Update a finder based on its _id
      operationId: updateFinder
      parameters:
        - required: true
          name: _id
          description: _id of the finder to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                keyword:
                  type: string
                minPrice:
                  type: number
                maxPrice:
                  type: number
                startDate:
                  type: string
                endDate:
                  type: string
        description: Finder to be updated
        required: true
      responses:
        "204":
          description: Finder updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      description: Deletes a single finder based on its _id
      operationId: deleteFinder
      parameters:
        - required: true
          name: _id
          description: _id of the finder to delete
          in: path
          schema:
            type: string
      responses:
        "204":
          description: Finder deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips:
    get:
      tags:
        - Trips
      description: Returns all trips
      operationId: getTrip
      responses:
        200:
          description: Trip list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/trip"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      tags:
        - Trips
      description: Creates a new trip
      operationId: addTrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trip"
        description: Trip to be created
        required: true
      responses:
        201:
          description: Trip
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{_id}:
    get:
      tags:
        - Trips
      description: Returns a single trip by its _id
      operationId: findBy_id
      parameters:
        - required: true
          name: _id
          description: _id of the trip to fetch
          in: path
          schema:
            type: string
      responses:
        200:
          description: Trip found by _id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trip"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      tags:
        - Trips
      description: Update a trip based on its _id
      operationId: updateTrip
      parameters:
        - required: true
          name: _id
          description: _id of the trip to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trip"
        description: Trip to be updated
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      tags:
        - Trips
      description: Deletes a single trip based on its _id
      operationId: deleteTrip
      parameters:
        - required: true
          name: _id
          description: _id of the trip to delete
          in: path
          schema:
            type: string
      responses:
        "204":
          description: Trip deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/manager/{managerId}:
    get:
      tags:
        - Trips
      description: Returns all manager trips
      operationId: aggregate
      parameters:
        - required: true
          name: managerId
          description: id of the manager logged into the system
          in: path
          schema:
            type: string
      responses:
        200:
          description: Trips found by managerId
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trip"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{id}/publish:
    patch:
      tags:
        - Trips
      description: Publish a trip
      operationId: publishTrip
      parameters:
        - required: true
          name: id
          description: _id of the trip to publish
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: Trip to be published
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{id}/cancel:
    patch:
      tags:
        - Trips
      description: Cancel a trip
      operationId: cancelTrip
      parameters:
        - required: true
          name: id
          description: _id of the trip to cancel
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cancelationReason:
                  type: string
        description: Trip to be cancelled
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/sponsorships/sponsor/{id}:
    get:
      tags:
        - Trips
      description: Returns all sponsorships by sponsor_id
      operationId: findSponsorshipsBySponsorId
      parameters:
        - required: true
          name: id
          description: _id of the sponsor
          in: path
          schema:
            type: string
      responses:
        200:
          description: Sponsorships from the sponsor
          content:
            application/json:
              schema:
              type: array
              properties:
                type: object
                properties:
                  banner:
                    type: string
                  landingPage:
                    type: string
                  amount:
                    type: number
                  status:
                    type: string
                  sponsor_id:
                    type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/sponsorships/{id}:
    get:
      tags:
        - Trips
      description: Returns a sponsorship from a trip by id
      operationId: getTripSponsorshipById
      parameters:
        - required: true
          name: id
          description: _id of the sponsorship
          in: path
          schema:
            type: string
      responses:
        200:
          description: Sponsorship from a trip
          content:
            application/json:
              schema:
              type: array
              properties:
                type: object
                properties:
                  banner:
                    type: string
                  landingPage:
                    type: string
                  amount:
                    type: number
                  status:
                    type: string
                  sponsor_id:
                    type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{id}/sponsorships:
    put:
      tags:
        - Trips
      description: Add a sponsorship to a trip
      operationId: addSponsorship
      parameters:
        - required: true
          name: id
          description: _id of the trip to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                banner:
                  type: string
                landingPage:
                  type: string
                amount:
                  type: number
                status:
                  type: string
                sponsor_id:
                  type: string
        description: Sponsorship added to trip
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{tripId}/sponsorships/{sponsorshipId}:
    put:
      tags:
        - Trips
      description: Update a sponsorship from a trip
      operationId: updateTripSponsorship
      parameters:
        - required: true
          name: tripId
          description: _id of the trip to update
          in: path
          schema:
            type: string
        - required: true
          name: sponsorshipId
          description: _id of the sponsorship to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                banner:
                  type: string
                landingPage:
                  type: string
                amount:
                  type: number
                status:
                  type: string
                sponsor_id:
                  type: string
        description: Sponsorship from a trip to be updated
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/trips/{tripId}/sponsorships/{sponsorshipId}/change-status:
    patch:
      tags:
        - Trips
      description: Update status from a sponsorship
      operationId: updateTripSponsorshipStatus
      parameters:
        - required: true
          name: tripId
          description: _id of the trip to update
          in: path
          schema:
            type: string
        - required: true
          name: sponsorshipId
          description: _id of the sponsorship to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
        description: Sponsorship from a trip to be updated
        required: true
      responses:
        "204":
          description: Trip updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/configurations:
    get:
      description: Returns all configurations
      operationId: getConfiguration
      responses:
        200:
          description: Configuration list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/configuration"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Creates a new configuration
      operationId: addConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/configuration"
        description: Configuration to be created
        required: true
      responses:
        201:
          description: Configuration
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/configurations/{_id}:
    get:
      description: Returns a single configuration by its _id
      operationId: findBy_id
      parameters:
        - required: true
          name: _id
          description: _id of the configuration to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Configuration found by _id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/configuration"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Update a configuration based on its _id
      operationId: updateConfiguration
      parameters:
        - required: true
          name: _id
          description: _id of the configuration to update
          in: path
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/configuration"
        description: Configuration to be updated
        required: true
      responses:
        "204":
          description: Configuration updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      description: Deletes a single configuration based on its _id
      operationId: deleteConfiguration
      parameters:
        - required: true
          name: _id
          description: _id of the configuration to delete
          in: path
          schema:
            type: number
      responses:
        "204":
          description: Configuration deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  $ref:
    - "./components/schemas/actor.yaml"
    - "./components/schemas/application.yaml"
    - "./components/schemas/finder.yaml"
    - "./components/schemas/trip.yaml"
    - "./components/schemas/configuration.yaml"
    - "./components/schemas/error.yaml"
    - "./components/schemas/validation-error.yaml"
    - "./components/schemas/not-found-error.yaml"
